<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZP2skaG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZP2skaG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZP2skaG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZP2skaG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZP2skaG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZP2skaG',
    'container.build_id' => 'f358a6d0',
    'container.build_time' => 1691158438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZP2skaG');
